services:
  - type: web
    name: BriRummy500
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
